# Generated by Django 5.2 on 2025-04-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_confirmation_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
